# Generated by Django 4.2.20 on 2025-04-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='district',
            field=models.CharField(default='Не указан', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='Не указан', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(default='Не указан', max_length=255),
        ),
    ]
