# Generated by Django 4.2.20 on 2025-06-04 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('telegram_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PavilionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpv_code', models.CharField(max_length=100)),
                ('stop_name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('pavilion_number', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Павильон нового типа', 'Павильон нового типа'), ('Павильон старого типа', 'Павильон старого типа'), ('Павильон инн. типа', 'Павильон инн. типа'), ('Белый пилон', 'Белый пилон'), ('Черный пилон', 'Черный пилон'), ('Флаг', 'Флаг'), ('Информационное табло', 'Информационное табло')], max_length=100)),
                ('pavilion_class', models.CharField(max_length=100)),
                ('balance_holder', models.CharField(choices=[('Мосгортранс', 'Мосгортранс'), ('Московский Метрополитен', 'Московский Метрополитен')], max_length=100)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Баланс', 'Баланс'), ('До приемки', 'До приемки'), ('Планируемый', 'Планируемый'), ('Принят комп.', 'Принят комп.'), ('Тех. приемка', 'Тех. приемка')], max_length=100)),
                ('requires_repair', models.BooleanField(default=False)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifier.district')),
            ],
        ),
        migrations.CreateModel(
            name='RepairOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('assigned', 'Назначен'), ('in_progress', 'В работе'), ('done', 'Выполнен')], default='new', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('pavilion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='classifier.pavilioncard')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='classifier.district')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'unique_together': {('name', 'district')},
            },
        ),
        migrations.AddField(
            model_name='pavilioncard',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifier.region'),
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('predicted_class', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('confirmed_state', models.CharField(blank=True, max_length=100)),
                ('pavilion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='classifier.pavilioncard')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classifier.district'),
        ),
        migrations.AddField(
            model_name='employee',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='employee',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classifier.region'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='RepairOrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_orders', to='classifier.imageupload')),
                ('repair_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='classifier.repairorder')),
            ],
            options={
                'unique_together': {('repair_order', 'image')},
            },
        ),
    ]
