# Generated by Django 4.2.20 on 2025-04-20 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='imageupload',
            name='confirmed_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='predicted_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='classifier.district')),
            ],
        ),
        migrations.CreateModel(
            name='PavilionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpv_code', models.CharField(max_length=100)),
                ('stop_name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('pavilion_number', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=100)),
                ('pavilion_class', models.CharField(max_length=100)),
                ('balance_holder', models.CharField(choices=[('Город', 'Город'), ('Частная', 'Частная')], max_length=100)),
                ('address', models.TextField(blank=True)),
                ('confirmed_state', models.CharField(blank=True, max_length=100)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifier.district')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifier.region')),
            ],
        ),
        migrations.AddField(
            model_name='imageupload',
            name='pavilion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classifier.pavilioncard'),
        ),
    ]
