# Generated by Django 4.2.20 on 2025-04-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_district_imageupload_confirmed_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='predicted_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
