# Generated by Django 4.2.20 on 2025-04-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_alter_region_options_alter_region_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='image',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='image_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
