# Generated by Django 4.2.20 on 2025-04-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0005_remove_imageupload_image_imageupload_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image_url',
            field=models.URLField(),
        ),
    ]
