# Generated by Django 4.2.20 on 2025-04-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0006_alter_imageupload_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
    ]
