# Generated by Django 4.2.20 on 2025-05-01 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0007_alter_imageupload_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='pavilion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='classifier.pavilioncard'),
        ),
    ]
