# Generated by Django 4.2.20 on 2025-05-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0009_employee_repairorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pavilioncard',
            name='balance_holder',
            field=models.CharField(choices=[('Мосгортранс', 'Мосгортранс'), ('Московский Метрополитен', 'Московский Метрополитен')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pavilioncard',
            name='category',
            field=models.CharField(choices=[('Павильон нового типа', 'Павильон нового типа'), ('Павильон старого типа', 'Павильон старого типа'), ('Павильон инн. типа', 'Павильон инн. типа'), ('Белый пилон', 'Белый пилон'), ('Черный пилон', 'Черный пилон'), ('Флаг', 'Флаг'), ('Информационное табло', 'Информационное табло')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pavilioncard',
            name='confirmed_state',
            field=models.CharField(choices=[('Баланс', 'Баланс'), ('До приемки', 'До приемки'), ('Планируемый', 'Планируемый'), ('Принят комп.', 'Принят комп.'), ('Тех. приемка', 'Тех. приемка')], max_length=100),
        ),
    ]
