# Generated by Django 4.2.20 on 2025-05-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0010_alter_pavilioncard_balance_holder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pavilioncard',
            old_name='confirmed_state',
            new_name='status',
        ),
    ]
