# Generated by Django 4.2.20 on 2025-05-15 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0011_rename_confirmed_state_pavilioncard_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='telegram_chat_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='telegram_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
