# Generated by Django 4.2.20 on 2025-05-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0012_remove_employee_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
