# Generated by Django 4.2.20 on 2025-05-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0014_fill_telegram_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='telegram_token',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True),
        ),
    ]
