# Generated by Django 4.2.20 on 2025-05-15 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0017_regenerate_telegram_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='telegram_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
