version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: pavilion_audit
      POSTGRES_USER: AdminUser
      POSTGRES_PASSWORD: ADUSER
    ports:
      - "5432:5432"

  redis:
    image: redis:7

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    command: >
      sh -c "
        python manage.py migrate &&
        gunicorn image_classifier.wsgi:application --bind 0.0.0.0:8000
      "
    ports:
      - "8000:8000"

  celery:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    command: celery -A image_classifier worker --loglevel=info
    depends_on:
      - backend
      - redis

  telegram:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - backend
    command: python manage.py runbot

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./certbot-etc:/etc/letsencrypt:ro
      - ./certbot-var:/var/lib/letsencrypt:ro

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./frontend/dist:/var/www/html
    entrypoint: sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/html && sleep 12h; done"

volumes:
  postgres_data:
  certbot-etc:
  certbot-var:
