worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    upstream backend {
        server backend:8000;
    }

    upstream telegram {
        server telegram:8443;
    }

    # HTTP → HTTPS
    server {
        listen 80;
        server_name pavilion-classifier.ru www.pavilion-classifier.ru;
        return 301 https://$host$request_uri;
    }

    # HTTPS
    server {
        listen 443 ssl;
        server_name pavilion-classifier.ru www.pavilion-classifier.ru;

        ssl_certificate     /etc/letsencrypt/live/pavilion-classifier.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/pavilion-classifier.ru/privkey.pem;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;
        client_max_body_size 50M;

        # SPA
        location / {
            root   /usr/share/nginx/html;
            index  index.html;
            try_files $uri $uri/ /index.html;
        }

        # API
        location /api/ {
            resolver 127.0.0.11;
            proxy_pass       http://backend;
            proxy_set_header Host      $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Telegram webhook
        location ^~ /telegram/webhook {
        resolver 127.0.0.11;
        proxy_pass       http://telegram;
        proxy_set_header Host      $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    }
}
